# Generated by Django 3.1.2 on 2020-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
